export default {
  URL: 'http://localhost:5000/api/posts/',
  Uploads: 'uploads',
  Upload: 'upload',
  InsertLanguage: 'insert_language',
  InsertInterest: 'insert_interest',
  GetUserLanguage: 'get_language',
  GetUserInterest: 'get_interest',
  GetUserDetails: 'details',
  UpdateUserProfile: 'update_profile',
  RemoveLanguage: 'remove_language',
  RemoveInterest: 'remove_interest',
  RemoveImage: 'remove_image',
  SetProfilePic: 'set_profile_pic',
  RegisterUser: 'register_user',
  LoginUser: 'login_user',
  relationship: 'Relationship',
  height: 'Height',
  age: 'Age',
  race: 'Race',
  hair: 'Hair'
}
